spring.application.name=cursolar

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cursosdb?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=abc,123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Inicializa o schema.sql ao subir
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
# Permite que ALTERs de migracao falhem em bancos ja atualizados
spring.sql.init.continue-on-error=true

# Upload de arquivos
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Diretório onde os arquivos enviados serão salvos (ajuste conforme seu sistema)
app.upload.dir=uploads

# Thymeleaf
spring.thymeleaf.cache=false
